name: icegraph
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal
  - rasterio
  - pip  # We explicitly ask for pip to handle the next section

  - pip:
    # Computer Vision (Headless = no GUI, perfect for Docker)
    - opencv-python-headless
    # PyTorch (CPU version to keep image small & fast)
    - torch --index-url https://download.pytorch.org/whl/cpu
    - torchvision --index-url https://download.pytorch.org/whl/cpu
    - torchaudio --index-url https://download.pytorch.org/whl/cpu
    # Graph Neural Networks
    - torch_geometric
    # Data Science & Dev Tools
    - jupyter
    - numpy
    - pandas
    - matplotlib
    - scikit-image
    - pre-commit
    - flake8
    - black
